//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM1_Maximo.SapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SapService.Z_CognosIN")]
    public interface Z_CognosIN {
        
        // CODEGEN: Контракт генерации сообщений с операцией ZPPM_COGNOS_IN_FIN_PLAN не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CognosIN:ZPPM_COGNOS_IN_FIN_PLANRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse1 ZPPM_COGNOS_IN_FIN_PLAN(TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CognosIN:ZPPM_COGNOS_IN_FIN_PLANRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse1> ZPPM_COGNOS_IN_FIN_PLANAsync(TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPPM_COGNOS_IN_FIN_PLAN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZPPMS_COGNOS_IMPORT iS_PARAMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZPPMS_COGNOS_IMPORT IS_PARAMS {
            get {
                return this.iS_PARAMSField;
            }
            set {
                this.iS_PARAMSField = value;
                this.RaisePropertyChanged("IS_PARAMS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPPMS_COGNOS_IMPORT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iV_IBM_ID_DZOField;
        
        private string iV_IBM_NAME_DZOField;
        
        private string iV_IBM_ID_VERField;
        
        private string iV_IBM_NAME_VERField;
        
        private string iV_IBM_ID_FINTPField;
        
        private string iV_IBM_NAME_FINTPField;
        
        private string iV_IBM_ID_ITEMField;
        
        private string iV_IBM_NAME_ITEMField;
        
        private string iV_IBM_ID_DEFField;
        
        private string iV_IBM_KVField;
        
        private string iV_IBM_YEARField;
        
        private string iV_IBM_ID_MEASField;
        
        private string iV_IBM_CURRENCYField;
        
        private decimal iV_IBM_AMOUNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IV_IBM_ID_DZO {
            get {
                return this.iV_IBM_ID_DZOField;
            }
            set {
                this.iV_IBM_ID_DZOField = value;
                this.RaisePropertyChanged("IV_IBM_ID_DZO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IV_IBM_NAME_DZO {
            get {
                return this.iV_IBM_NAME_DZOField;
            }
            set {
                this.iV_IBM_NAME_DZOField = value;
                this.RaisePropertyChanged("IV_IBM_NAME_DZO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_IBM_ID_VER {
            get {
                return this.iV_IBM_ID_VERField;
            }
            set {
                this.iV_IBM_ID_VERField = value;
                this.RaisePropertyChanged("IV_IBM_ID_VER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IV_IBM_NAME_VER {
            get {
                return this.iV_IBM_NAME_VERField;
            }
            set {
                this.iV_IBM_NAME_VERField = value;
                this.RaisePropertyChanged("IV_IBM_NAME_VER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IV_IBM_ID_FINTP {
            get {
                return this.iV_IBM_ID_FINTPField;
            }
            set {
                this.iV_IBM_ID_FINTPField = value;
                this.RaisePropertyChanged("IV_IBM_ID_FINTP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IV_IBM_NAME_FINTP {
            get {
                return this.iV_IBM_NAME_FINTPField;
            }
            set {
                this.iV_IBM_NAME_FINTPField = value;
                this.RaisePropertyChanged("IV_IBM_NAME_FINTP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IV_IBM_ID_ITEM {
            get {
                return this.iV_IBM_ID_ITEMField;
            }
            set {
                this.iV_IBM_ID_ITEMField = value;
                this.RaisePropertyChanged("IV_IBM_ID_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IV_IBM_NAME_ITEM {
            get {
                return this.iV_IBM_NAME_ITEMField;
            }
            set {
                this.iV_IBM_NAME_ITEMField = value;
                this.RaisePropertyChanged("IV_IBM_NAME_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IV_IBM_ID_DEF {
            get {
                return this.iV_IBM_ID_DEFField;
            }
            set {
                this.iV_IBM_ID_DEFField = value;
                this.RaisePropertyChanged("IV_IBM_ID_DEF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string IV_IBM_KV {
            get {
                return this.iV_IBM_KVField;
            }
            set {
                this.iV_IBM_KVField = value;
                this.RaisePropertyChanged("IV_IBM_KV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IV_IBM_YEAR {
            get {
                return this.iV_IBM_YEARField;
            }
            set {
                this.iV_IBM_YEARField = value;
                this.RaisePropertyChanged("IV_IBM_YEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string IV_IBM_ID_MEAS {
            get {
                return this.iV_IBM_ID_MEASField;
            }
            set {
                this.iV_IBM_ID_MEASField = value;
                this.RaisePropertyChanged("IV_IBM_ID_MEAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string IV_IBM_CURRENCY {
            get {
                return this.iV_IBM_CURRENCYField;
            }
            set {
                this.iV_IBM_CURRENCYField = value;
                this.RaisePropertyChanged("IV_IBM_CURRENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal IV_IBM_AMOUNT {
            get {
                return this.iV_IBM_AMOUNTField;
            }
            set {
                this.iV_IBM_AMOUNTField = value;
                this.RaisePropertyChanged("IV_IBM_AMOUNT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPPM_COGNOS_IN_FIN_PLAN_RESULT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short eRRORField;
        
        private string tEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TEXT {
            get {
                return this.tEXTField;
            }
            set {
                this.tEXTField = value;
                this.RaisePropertyChanged("TEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPPM_COGNOS_IN_FIN_PLANResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZPPM_COGNOS_IN_FIN_PLAN_RESULT eS_RESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZPPM_COGNOS_IN_FIN_PLAN_RESULT ES_RESULT {
            get {
                return this.eS_RESULTField;
            }
            set {
                this.eS_RESULTField = value;
                this.RaisePropertyChanged("ES_RESULT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZPPM_COGNOS_IN_FIN_PLANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLAN ZPPM_COGNOS_IN_FIN_PLAN;
        
        public ZPPM_COGNOS_IN_FIN_PLANRequest() {
        }
        
        public ZPPM_COGNOS_IN_FIN_PLANRequest(TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLAN ZPPM_COGNOS_IN_FIN_PLAN) {
            this.ZPPM_COGNOS_IN_FIN_PLAN = ZPPM_COGNOS_IN_FIN_PLAN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZPPM_COGNOS_IN_FIN_PLANResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse ZPPM_COGNOS_IN_FIN_PLANResponse;
        
        public ZPPM_COGNOS_IN_FIN_PLANResponse1() {
        }
        
        public ZPPM_COGNOS_IN_FIN_PLANResponse1(TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse ZPPM_COGNOS_IN_FIN_PLANResponse) {
            this.ZPPM_COGNOS_IN_FIN_PLANResponse = ZPPM_COGNOS_IN_FIN_PLANResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_CognosINChannel : TM1_Maximo.SapService.Z_CognosIN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_CognosINClient : System.ServiceModel.ClientBase<TM1_Maximo.SapService.Z_CognosIN>, TM1_Maximo.SapService.Z_CognosIN {
        
        public Z_CognosINClient() {
        }
        
        public Z_CognosINClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_CognosINClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CognosINClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CognosINClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse1 TM1_Maximo.SapService.Z_CognosIN.ZPPM_COGNOS_IN_FIN_PLAN(TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANRequest request) {
            return base.Channel.ZPPM_COGNOS_IN_FIN_PLAN(request);
        }
        
        public TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse ZPPM_COGNOS_IN_FIN_PLAN(TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLAN ZPPM_COGNOS_IN_FIN_PLAN1) {
            TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANRequest inValue = new TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANRequest();
            inValue.ZPPM_COGNOS_IN_FIN_PLAN = ZPPM_COGNOS_IN_FIN_PLAN1;
            TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse1 retVal = ((TM1_Maximo.SapService.Z_CognosIN)(this)).ZPPM_COGNOS_IN_FIN_PLAN(inValue);
            return retVal.ZPPM_COGNOS_IN_FIN_PLANResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse1> TM1_Maximo.SapService.Z_CognosIN.ZPPM_COGNOS_IN_FIN_PLANAsync(TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANRequest request) {
            return base.Channel.ZPPM_COGNOS_IN_FIN_PLANAsync(request);
        }
        
        public System.Threading.Tasks.Task<TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANResponse1> ZPPM_COGNOS_IN_FIN_PLANAsync(TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLAN ZPPM_COGNOS_IN_FIN_PLAN) {
            TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANRequest inValue = new TM1_Maximo.SapService.ZPPM_COGNOS_IN_FIN_PLANRequest();
            inValue.ZPPM_COGNOS_IN_FIN_PLAN = ZPPM_COGNOS_IN_FIN_PLAN;
            return ((TM1_Maximo.SapService.Z_CognosIN)(this)).ZPPM_COGNOS_IN_FIN_PLANAsync(inValue);
        }
    }
}
